---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: flux-source-controller
spec:
  serviceAccountName: default-sa
  packageRef:
    refName: flux.source.controller.apps.tanzu.vmware.com
    versionSelection:
      constraints: 0.16.0
---
apiVersion: v1
kind: Secret
metadata:
  name: flux-source-controller-values
stringData:
  values.yml: |
    ---
    service_port: 80
